---
apiVersion: apps/v
kind: Deployment
metadata:
 name: contactfrontendappdeployment
spec:
 replicas: 2
 selector:
   matchLabels:
    app: contactfrontend
 template:
   metadata: 
    name: contactfrontend
    labels:
      app: contactfrontend
   spec:
    containers:
    - name: contactfrontendcontainer
      image: mouni9948/myuiapp
      ports:
      - containerPort: 80
---


apiVersion: v1
kind: Service
metadata:
  name: contactfrontendsvc
spec:
  type: NodePort
  selector:
    app: contactfrontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3000
...

